/**
* Used for objects that react to water such as wind gust and plants. Generated by water material
*/
public class WaterEffect : AEffect {
    public float WaterDensity {get; private set;}

    public WaterEffect SetWaterDensity(float density) {
        WaterDensity = density;
        return this;
    }
}
